# Generated by Django 4.2.3 on 2024-01-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendee',
            table='data',
        ),
    ]
