# Generated by Django 4.2.3 on 2024-01-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_attendee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendee',
            table=None,
        ),
    ]
